[tox]
envlist=linting,unittesting
minversion = 4.0
skipsdist = True
toxworkdir=/tmp/.tox

[testenv]
passenv = *

usedevelop = True
install_command = pip install -U {opts} {packages}
deps = -e {env:HOME}/fusion-common
       -e {env:HOME}/fusion-agent
       -e {env:HOME}/fusion-manager/mgmtworker
       -r{toxinidir}/requirements.txt
       -r{toxinidir}/test-requirements.txt
whitelist_externals = bash

[testenv:unittesting]
commands =
    pytest -vv -s cloudify_aws_sdk/tests/
    pytest -vv -s cloudify_kubernetes_sdk/tests/
    pytest -vv -s cloudify_common_sdk/tests/test_cli_tool_base.py
    pytest -vv -s cloudify_common_sdk/tests/test_deprecation.py
    nose2 -v cloudify_common_sdk
    nose2 -v cloudify_rest_sdk
    nose2 -v cloudify_terminal_sdk

[testenv:linting]
commands =
    flake8 cloudify_aws_sdk
    flake8 cloudify_rest_sdk
    flake8 cloudify_common_sdk
    flake8 cloudify_terminal_sdk
    flake8 cloudify_kubernetes_sdk
